"""Standard legal disclaimers for all client-facing outputs."""

REGINTEL_DISCLAIMER = (
    "RegIntel provides informational regulatory-change intelligence generated by an AI "
    "system and is not a substitute for legal advice. Always consult a qualified "
    "compliance professional or attorney before making compliance decisions. RegIntel "
    "makes reasonable efforts to verify citations but does not guarantee completeness "
    "or accuracy."
)
